### ISSUE TITLE
Report bugs link has typo in URL

### ISSUE THREAD

**Issue by VA1DER** [ternite/dokuwiki-plugin-mediathumbnails#3]
The "report bugs" link has a typo in the url, pointing to: "hhttps://github.com/ternite/dokuwiki-plugin-mediathumbnails/issues"

**Comment by Michaelsy** [comment]
It's a wiki, you can correct it yourself. (I have already done so.)

\- Michael Sy.

**Comment by VA1DER** [comment]
Oh, of course.  I didn't even stop to think.  I get to the doc page from inside my plugin, it just seemed to be part of the plugin.  Thanks.
